//! Auto-generated stub module for feature: training
//! This file was automatically generated by tools/stub_generator/
//! Manual edits may be overwritten.

const std = @import("std");
const config_module = @import("../../core/config/mod.zig");
const shared_types = @import("types.zig");

pub const types = shared_types;
pub const Error = shared_types.Error;
pub const Config = shared_types.Config;
pub const Context = shared_types.Context;
pub const State = shared_types.State;

pub const Error = error{
    TrainingDisabled,
};

pub const Context = struct {
    allocator: std.mem.Allocator = undefined,
    config: config_module.TrainingDisabledConfig = .{},

    pub fn init(_: std.mem.Allocator, _: config_module.TrainingDisabledConfig) !*Context {
        return error.TrainingDisabled;
    }

    pub fn deinit(_: *Context) void {}
};

pub fn init(_: std.mem.Allocator, _: config_module.TrainingDisabledConfig) Error!void {
    return error.TrainingDisabled;
}

pub fn deinit() void {}

pub fn isEnabled() bool {
    return false;
}

pub const InstructionSample = struct {
    pub fn init(_: std.mem.Allocator, _: config_module.TrainingDisabledConfig) !*Context {
        return error.TrainingDisabled;
    }

    pub fn deinit(_: *InstructionSample) void {}
};

pub const parseInstructionDataset = struct {
    pub fn init(_: std.mem.Allocator, _: config_module.TrainingDisabledConfig) !*Context {
        return error.TrainingDisabled;
    }

    pub fn deinit(_: *parseInstructionDataset) void {}
};

test {
    std.testing.refAllDecls(@This());
}