version: 2
updates:
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "maintainer-username"  # Replace with actual maintainer username
    assignees:
      - "maintainer-username"  # Replace with actual maintainer username
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"

  # Enable version updates for Zig (if using zigmod or similar)
  - package-ecosystem: "zig"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "maintainer-username"  # Replace with actual maintainer username
    assignees:
      - "maintainer-username"  # Replace with actual maintainer username
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "zig"
