//! Auto-generated stub module for feature: prompts
//! This file was automatically generated by tools/stub_generator/
//! Manual edits may be overwritten.

const std = @import("std");
const config_module = @import("../../core/config/mod.zig");
const shared_types = @import("types.zig");

pub const types = shared_types;

pub const Error = error{
    PromptsDisabled,
};

pub fn isEnabled() bool {
    return false;
}

test {
    std.testing.refAllDecls(@This());
}