//! Auto-generated stub module for feature: templates
//! This file was automatically generated by tools/stub_generator/
//! Manual edits may be overwritten.

const std = @import("std");
const config_module = @import("../../core/config/mod.zig");
const shared_types = @import("types.zig");

pub const types = shared_types;
pub const Error = shared_types.Error;
pub const Options = shared_types.Options;

pub const Error = error{
    TemplatesDisabled,
};

pub fn init(_: std.mem.Allocator, _: config_module.TemplatesDisabledConfig) Error!void {
    return error.TemplatesDisabled;
}

pub fn deinit() void {}

pub fn isEnabled() bool {
    return false;
}

test {
    std.testing.refAllDecls(@This());
}