//! Auto-generated stub module for feature: reasoning
//! This file was automatically generated by tools/stub_generator/
//! Manual edits may be overwritten.

const std = @import("std");
const config_module = @import("../../core/config/mod.zig");
const shared_types = @import("types.zig");

pub const types = shared_types;
pub const Config = shared_types.Config;
pub const Context = shared_types.Context;
pub const State = shared_types.State;

pub const Error = error{
    ReasoningDisabled,
};

pub const Context = struct {
    allocator: std.mem.Allocator = undefined,
    config: config_module.ReasoningDisabledConfig = .{},

    pub fn init(_: std.mem.Allocator, _: config_module.ReasoningDisabledConfig) !*Context {
        return error.ReasoningDisabled;
    }

    pub fn deinit(_: *Context) void {}
};

pub fn init(_: std.mem.Allocator, _: config_module.ReasoningDisabledConfig) Error!void {
    return error.ReasoningDisabled;
}

pub fn deinit() void {}

pub fn isEnabled() bool {
    return false;
}

test {
    std.testing.refAllDecls(@This());
}