const std = @import("std");
const registry = @import("registry.zig");

pub const CompletionShell = enum {
    bash,
    zsh,
    fish,
};

fn writeFmt(writer: anytype, allocator: std.mem.Allocator, comptime format: []const u8, args: anytype) !void {
    const rendered = try std.fmt.allocPrint(allocator, format, args);
    defer allocator.free(rendered);
    try writer.writeAll(rendered);
}

fn writeUniqueCompletionWord(writer: anytype, allocator: std.mem.Allocator, seen: *std.ArrayListUnmanaged([]const u8), word: []const u8) !void {
    for (seen.items) |item| {
        if (std.mem.eql(u8, item, word)) return;
    }
    try seen.append(allocator, word);
    try writeFmt(writer, allocator, "{s} ", .{word});
}

fn writeCompletionWordsForCommand(writer: anytype, allocator: std.mem.Allocator, command: registry.Command) !void {
    var seen = std.ArrayListUnmanaged([]const u8).empty;
    defer seen.deinit(allocator);

    for (command.subcommands) |subcommand| {
        try writeUniqueCompletionWord(writer, allocator, &seen, subcommand.name);
    }
    for (command.args) |a| {
        if (a.kind != .positional) try writeFmt(writer, allocator, "--{s} ", .{a.name});
        for (a.choices) |choice| try writeUniqueCompletionWord(writer, allocator, &seen, choice);
    }
}

fn writeHelpCompletionWords(writer: anytype, allocator: std.mem.Allocator) !void {
    var seen = std.ArrayListUnmanaged([]const u8).empty;
    defer seen.deinit(allocator);

    try writeUniqueCompletionWord(writer, allocator, &seen, "--json");
    try writeUniqueCompletionWord(writer, allocator, &seen, "--completion");
    try writeUniqueCompletionWord(writer, allocator, &seen, "bash");
    try writeUniqueCompletionWord(writer, allocator, &seen, "zsh");
    try writeUniqueCompletionWord(writer, allocator, &seen, "fish");
    for (registry.commands) |help_command| try writeUniqueCompletionWord(writer, allocator, &seen, help_command.name);
    for (registry.shortcuts) |shortcut| try writeUniqueCompletionWord(writer, allocator, &seen, shortcut.token);
}

fn writeBashCaseLabel(writer: anytype, allocator: std.mem.Allocator, command: registry.Command) !void {
    try writeFmt(writer, allocator, "    {s}", .{command.name});
    for (registry.shortcuts) |shortcut| {
        if (std.mem.eql(u8, shortcut.command, command.name)) {
            try writeFmt(writer, allocator, "|{s}", .{shortcut.token});
        }
    }
    try writer.writeAll(")\n");
}

fn writeBashCompletion(writer: anytype, allocator: std.mem.Allocator) !void {
    try writer.writeAll(
        \\# abi bash completion; generated by `abi help --completion bash`
        \\_abi_complete() {
        \\  local cur cmd words
        \\  COMPREPLY=()
        \\  cur="${COMP_WORDS[COMP_CWORD]}"
        \\  if [[ ${COMP_CWORD} -eq 1 ]]; then
        \\    words="
    );
    for (registry.commands) |command| try writeFmt(writer, allocator, "{s} ", .{command.name});
    for (registry.shortcuts) |shortcut| try writeFmt(writer, allocator, "{s} ", .{shortcut.token});
    try writer.writeAll(
        \\"
        \\    COMPREPLY=( $(compgen -W "$words" -- "$cur") )
        \\    return 0
        \\  fi
        \\  cmd="${COMP_WORDS[1]}"
        \\  case "$cmd" in
    );
    try writer.writeAll("\n");
    for (registry.commands) |command| {
        try writeBashCaseLabel(writer, allocator, command);
        try writer.writeAll("      words=\"");
        if (std.mem.eql(u8, command.name, "help")) {
            try writeHelpCompletionWords(writer, allocator);
        } else {
            try writeCompletionWordsForCommand(writer, allocator, command);
        }
        try writer.writeAll(
            \\"
            \\      COMPREPLY=( $(compgen -W "$words" -- "$cur") )
            \\      ;;
        );
        try writer.writeAll("\n");
    }
    try writer.writeAll(
        \\  esac
        \\}
        \\complete -F _abi_complete abi
        \\
    );
}

fn writeZshCompletion(writer: anytype, allocator: std.mem.Allocator) !void {
    try writer.writeAll(
        \\#compdef abi
        \\# abi zsh completion; generated by `abi help --completion zsh`
        \\local -a commands
        \\commands=(
    );
    for (registry.commands) |command| try writeFmt(writer, allocator, "  {s}\n", .{command.name});
    for (registry.shortcuts) |shortcut| try writeFmt(writer, allocator, "  {s}\n", .{shortcut.token});
    try writer.writeAll(
        \\)
        \\if (( CURRENT == 2 )); then
        \\  compadd -- $commands
        \\  return
        \\fi
        \\local cmd="${words[2]}"
        \\case "$cmd" in
    );
    try writer.writeAll("\n");
    for (registry.commands) |command| {
        try writeBashCaseLabel(writer, allocator, command);
        try writer.writeAll("      compadd -- ");
        if (std.mem.eql(u8, command.name, "help")) {
            try writeHelpCompletionWords(writer, allocator);
        } else {
            try writeCompletionWordsForCommand(writer, allocator, command);
        }
        try writer.writeAll("\n      ;;\n");
    }
    try writer.writeAll("esac\n");
}

fn writeFishCompletion(writer: anytype, allocator: std.mem.Allocator) !void {
    try writer.writeAll(
        \\# abi fish completion; generated by `abi help --completion fish`
        \\complete -c abi -f
        \\complete -c abi -n '__fish_use_subcommand' -a '
    );
    for (registry.commands) |command| try writeFmt(writer, allocator, "{s} ", .{command.name});
    for (registry.shortcuts) |shortcut| try writeFmt(writer, allocator, "{s} ", .{shortcut.token});
    try writer.writeAll("'\n");

    try writer.writeAll("complete -c abi -n '__fish_seen_subcommand_from help' -l json\n");
    try writer.writeAll("complete -c abi -n '__fish_seen_subcommand_from help' -l completion -a 'bash zsh fish'\n");
    for (registry.commands) |command| {
        if (std.mem.eql(u8, command.name, "help")) continue;
        const condition_prefix = "complete -c abi -n '__fish_seen_subcommand_from ";
        try writeFmt(writer, allocator, "{s}{s}", .{ condition_prefix, command.name });
        for (registry.shortcuts) |shortcut| {
            if (std.mem.eql(u8, shortcut.command, command.name)) try writeFmt(writer, allocator, " {s}", .{shortcut.token});
        }
        try writer.writeAll("' -a '");
        var seen = std.ArrayListUnmanaged([]const u8).empty;
        defer seen.deinit(allocator);
        for (command.subcommands) |subcommand| try writeUniqueCompletionWord(writer, allocator, &seen, subcommand.name);
        for (command.args) |a| {
            if (a.kind == .positional) {
                for (a.choices) |choice| try writeUniqueCompletionWord(writer, allocator, &seen, choice);
            }
        }
        try writer.writeAll("'\n");

        for (command.args) |a| {
            if (a.kind == .positional) continue;
            try writeFmt(writer, allocator, "{s}{s}", .{ condition_prefix, command.name });
            for (registry.shortcuts) |shortcut| {
                if (std.mem.eql(u8, shortcut.command, command.name)) try writeFmt(writer, allocator, " {s}", .{shortcut.token});
            }
            try writeFmt(writer, allocator, "' -l {s}", .{a.name});
            if (a.choices.len != 0) {
                try writer.writeAll(" -a '");
                for (a.choices) |choice| try writeFmt(writer, allocator, "{s} ", .{choice});
                try writer.writeAll("'");
            }
            try writer.writeAll("\n");
        }
    }
}

pub fn writeShellCompletion(writer: anytype, allocator: std.mem.Allocator, shell: CompletionShell) !void {
    switch (shell) {
        .bash => try writeBashCompletion(writer, allocator),
        .zsh => try writeZshCompletion(writer, allocator),
        .fish => try writeFishCompletion(writer, allocator),
    }
}

pub fn printShellCompletion(allocator: std.mem.Allocator, shell: CompletionShell) !u8 {
    const DebugWriter = struct {
        pub fn writeAll(_: *@This(), bytes: []const u8) !void {
            std.debug.print("{s}", .{bytes});
        }
    };
    var writer = DebugWriter{};
    try writeShellCompletion(&writer, allocator, shell);
    return 0;
}

test {
    std.testing.refAllDecls(@This());
}
