apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: abi-ai-framework-monitor
  labels:
    app: abi-ai-framework
spec:
  selector:
    matchLabels:
      app: abi-ai-framework
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      honorLabels: true
