//! Shell-completion generation from the live command and shortcut tables.
//!
//! The captured scripts under `tests/golden/` are compatibility oracles, not
//! production inputs. Keeping generation here means a command-table change is
//! observable even before the goldens are deliberately updated.

use std::fmt::Write as _;

use crate::usage::{COMMANDS, SHORTCUTS};

fn top_level_words() -> String {
    let mut words = String::new();
    for command in COMMANDS {
        write!(words, "{} ", command.name).expect("writing to a String cannot fail");
    }
    for shortcut in SHORTCUTS {
        write!(words, "{} ", shortcut.token).expect("writing to a String cannot fail");
    }
    words
}

fn command_words(name: &str) -> String {
    match name {
        "help" => format!("--json --completion bash zsh fish {}", top_level_words()),
        "complete" => {
            "--live --confirm --learn --soul --soul-alpha --stream --neural --model ".to_owned()
        }
        "agent" => "plan train tui multi spawn browser os ".to_owned(),
        "plugin" => "list run ".to_owned(),
        "auth" => "status logout signin ".to_owned(),
        "twilio" => "simulate ".to_owned(),
        "tui" | "dashboard" => "--pane 1 2 3 4 5 system plugins storage wdbx scheduler memory --plain --no-color --compact --once --interval --json --list-panes ".to_owned(),
        "wdbx" => "db block query benchmark simulate cluster compute secure gpu api ".to_owned(),
        "scheduler" => "status ".to_owned(),
        "nn" => "train sample --jsonl --field --text --seed --n ".to_owned(),
        _ => String::new(),
    }
}

fn case_label(name: &str) -> String {
    let mut label = name.to_owned();
    for shortcut in SHORTCUTS.iter().filter(|shortcut| shortcut.command == name) {
        write!(label, "|{}", shortcut.token).expect("writing to a String cannot fail");
    }
    label
}

fn seen_commands(name: &str) -> String {
    let mut commands = name.to_owned();
    for shortcut in SHORTCUTS.iter().filter(|shortcut| shortcut.command == name) {
        write!(commands, " {}", shortcut.token).expect("writing to a String cannot fail");
    }
    commands
}

fn render_bash() -> String {
    let mut output = String::from(concat!(
        "# abi bash completion; generated by `abi help --completion bash`\n",
        "_abi_complete() {\n",
        "  local cur cmd words\n",
        "  COMPREPLY=()\n",
        "  cur=\"${COMP_WORDS[COMP_CWORD]}\"\n",
        "  if [[ ${COMP_CWORD} -eq 1 ]]; then\n",
    ));
    writeln!(output, "    words=\"{}\"", top_level_words())
        .expect("writing to a String cannot fail");
    output.push_str(concat!(
        "    COMPREPLY=( $(compgen -W \"$words\" -- \"$cur\") )\n",
        "    return 0\n",
        "  fi\n",
        "  cmd=\"${COMP_WORDS[1]}\"\n",
        "  case \"$cmd\" in\n",
    ));
    for command in COMMANDS {
        writeln!(output, "    {})", case_label(command.name))
            .expect("writing to a String cannot fail");
        writeln!(output, "      words=\"{}\"", command_words(command.name))
            .expect("writing to a String cannot fail");
        output.push_str(concat!(
            "      COMPREPLY=( $(compgen -W \"$words\" -- \"$cur\") )\n",
            "      ;;\n",
        ));
    }
    output.push_str(concat!(
        "  esac\n",
        "}\n",
        "complete -F _abi_complete abi\n",
    ));
    output
}

fn render_zsh() -> String {
    let mut output = String::from(concat!(
        "#compdef abi\n",
        "# abi zsh completion; generated by `abi help --completion zsh`\n",
        "local -a commands\n",
        "commands=(",
    ));
    for command in COMMANDS {
        writeln!(output, "  {}", command.name).expect("writing to a String cannot fail");
    }
    for shortcut in SHORTCUTS {
        writeln!(output, "  {}", shortcut.token).expect("writing to a String cannot fail");
    }
    output.push_str(concat!(
        ")\n",
        "if (( CURRENT == 2 )); then\n",
        "  compadd -- $commands\n",
        "  return\n",
        "fi\n",
        "local cmd=\"${words[2]}\"\n",
        "case \"$cmd\" in\n",
    ));
    for command in COMMANDS {
        writeln!(output, "    {})", case_label(command.name))
            .expect("writing to a String cannot fail");
        writeln!(output, "      compadd -- {}", command_words(command.name))
            .expect("writing to a String cannot fail");
        output.push_str("      ;;\n");
    }
    output.push_str("esac\n");
    output
}

fn fish_line(output: &mut String, seen: &str, suffix: &str) {
    writeln!(
        output,
        "complete -c abi -n '__fish_seen_subcommand_from {seen}'{suffix}"
    )
    .expect("writing to a String cannot fail");
}

fn render_fish() -> String {
    let mut output = String::from(
        "# abi fish completion; generated by `abi help --completion fish`\n\
complete -c abi -f\n",
    );
    writeln!(
        output,
        "complete -c abi -n '__fish_use_subcommand' -a '{}'",
        top_level_words()
    )
    .expect("writing to a String cannot fail");

    for command in COMMANDS {
        let seen = seen_commands(command.name);
        match command.name {
            "help" => {
                fish_line(&mut output, &seen, " -l json");
                fish_line(&mut output, &seen, " -l completion -a 'bash zsh fish'");
            }
            "complete" => {
                fish_line(&mut output, &seen, " -a ''");
                for option in [
                    "live",
                    "confirm",
                    "learn",
                    "soul",
                    "soul-alpha",
                    "stream",
                    "neural",
                    "model",
                ] {
                    fish_line(&mut output, &seen, &format!(" -l {option}"));
                }
            }
            "agent" => fish_line(
                &mut output,
                &seen,
                " -a 'plan train tui multi spawn browser os '",
            ),
            "plugin" => fish_line(&mut output, &seen, " -a 'list run '"),
            "auth" => fish_line(&mut output, &seen, " -a 'status logout signin '"),
            "twilio" => fish_line(&mut output, &seen, " -a 'simulate '"),
            "tui" | "dashboard" => {
                fish_line(&mut output, &seen, " -a ''");
                fish_line(
                    &mut output,
                    &seen,
                    " -l pane -a '1 2 3 4 5 system plugins storage wdbx scheduler memory '",
                );
                for option in [
                    "plain",
                    "no-color",
                    "compact",
                    "once",
                    "interval",
                    "json",
                    "list-panes",
                ] {
                    fish_line(&mut output, &seen, &format!(" -l {option}"));
                }
            }
            "wdbx" => fish_line(
                &mut output,
                &seen,
                " -a 'db block query benchmark simulate cluster compute secure gpu api '",
            ),
            "scheduler" => fish_line(&mut output, &seen, " -a 'status '"),
            "nn" => {
                fish_line(&mut output, &seen, " -a 'train sample '");
                for option in ["jsonl", "field", "text", "seed", "n"] {
                    fish_line(&mut output, &seen, &format!(" -l {option}"));
                }
            }
            _ => fish_line(&mut output, &seen, " -a ''"),
        }
    }
    output
}

/// Render one of the frozen shell-completion formats.
#[must_use]
pub(crate) fn render(shell: &str) -> Option<String> {
    match shell {
        "bash" => Some(render_bash()),
        "zsh" => Some(render_zsh()),
        "fish" => Some(render_fish()),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_scripts_match_the_frozen_oracles_byte_for_byte() {
        for (shell, expected) in [
            (
                "bash",
                include_str!("../../../tests/golden/completion.bash"),
            ),
            ("zsh", include_str!("../../../tests/golden/completion.zsh")),
            (
                "fish",
                include_str!("../../../tests/golden/completion.fish"),
            ),
        ] {
            assert_eq!(render(shell).as_deref(), Some(expected), "{shell}");
        }
    }

    #[test]
    fn unsupported_shell_is_rejected() {
        assert_eq!(render("powershell"), None);
    }
}
