//! Auto-generated stub module for feature: coordination
//! This file was automatically generated by tools/stub_generator/
//! Manual edits may be overwritten.

const std = @import("std");
const config_module = @import("../../core/config/mod.zig");

pub const Error = error{
    CoordinationDisabled,
};

pub const Context = struct {
    allocator: std.mem.Allocator = undefined,
    config: config_module.CoordinationDisabledConfig = .{},

    pub fn init(_: std.mem.Allocator, _: config_module.CoordinationDisabledConfig) !*Context {
        return error.CoordinationDisabled;
    }

    pub fn deinit(_: *Context) void {}
};

pub fn init(_: std.mem.Allocator, _: config_module.CoordinationDisabledConfig) Error!void {
    return error.CoordinationDisabled;
}

pub fn deinit() void {}

pub fn isEnabled() bool {
    return false;
}

test {
    std.testing.refAllDecls(@This());
}