//! Auto-generated stub module for feature: profiles
//! This file was automatically generated by tools/stub_generator/
//! Manual edits may be overwritten.

const std = @import("std");
const config_module = @import("../../core/config/mod.zig");

pub const Error = error{
    ProfilesDisabled,
};

pub const Context = struct {
    allocator: std.mem.Allocator = undefined,

    pub fn init(_: std.mem.Allocator, _: config_module.ProfilesDisabledConfig) !*Context {
        return error.ProfilesDisabled;
    }

    pub fn deinit(_: *Context) void {}
};

pub fn init(_: std.mem.Allocator, _: config_module.ProfilesDisabledConfig) Error!void {
    return error.ProfilesDisabled;
}

pub fn deinit() void {}

pub fn isEnabled() bool {
    return false;
}

test {
    std.testing.refAllDecls(@This());
}