//! Auto-generated stub module for feature: abi
//! This file was automatically generated by tools/stub_generator/
//! Manual edits may be overwritten.

const std = @import("std");
const config_module = @import("../../core/config/mod.zig");

pub const Error = error{
    AbiDisabled,
};

pub fn init(_: std.mem.Allocator, _: config_module.AbiDisabledConfig) Error!void {
    return error.AbiDisabled;
}

pub fn deinit() void {}

pub fn isEnabled() bool {
    return false;
}

test {
    std.testing.refAllDecls(@This());
}