//! Auto-generated stub module for feature: streaming
//! This file was automatically generated by tools/stub_generator/
//! Manual edits may be overwritten.

const std = @import("std");
const config_module = @import("../../core/config/mod.zig");
const shared_types = @import("types.zig");

pub const types = shared_types;
pub const Error = shared_types.Error;
pub const Config = shared_types.Config;
pub const State = shared_types.State;

pub const Error = error{
    StreamingDisabled,
};

pub fn init(_: std.mem.Allocator, _: config_module.StreamingDisabledConfig) Error!void {
    return error.StreamingDisabled;
}

pub fn deinit() void {}

pub fn isEnabled() bool {
    return false;
}

test {
    std.testing.refAllDecls(@This());
}