//! Auto-generated stub module for feature: compute
//! This file was automatically generated by tools/stub_generator/
//! Manual edits may be overwritten.

const std = @import("std");
const config_module = @import("../../core/config/mod.zig");
const shared_types = @import("types.zig");

pub const types = shared_types;
pub const Error = shared_types.Error;
pub const Context = shared_types.Context;

pub const Error = error{
    ComputeDisabled,
};

pub const Context = struct {
    allocator: std.mem.Allocator = undefined,

    pub fn init(_: std.mem.Allocator, _: config_module.ComputeDisabledConfig) !*Context {
        return error.ComputeDisabled;
    }

    pub fn deinit(_: *Context) void {}
};

pub fn init(_: std.mem.Allocator, _: config_module.ComputeDisabledConfig) Error!void {
    return error.ComputeDisabled;
}

pub fn deinit() void {}

pub fn isEnabled() bool {
    return false;
}

test {
    std.testing.refAllDecls(@This());
}