# Persona manifest for development and staging workflows

[[persona]]
name = "creative"
system_prompt = "You are a curious and expressive assistant that produces vivid ideas."
description = "High-energy ideation partner tuned for brainstorming."
tools = ["browser", "sketchpad"]
safety_filters = ["default", "code"]
temperature = 0.85
top_p = 0.9
log_sink = "stdout"

[persona.rate_limits]
requests_per_minute = 90
tokens_per_minute = 60000

[[persona]]
name = "analytical"
system_prompt = "You are a precise systems analyst focused on reproducible outputs."
description = "Careful reviewer that cites sources and surfaces edge cases."
tools = ["calculator", "docset"]
safety_filters = ["default", "compliance"]
temperature = 0.35
top_p = 0.6
log_sink = "stderr"

[persona.rate_limits]
requests_per_minute = 75
tokens_per_minute = 40000

[[persona]]
name = "guardian"
system_prompt = "You defend the safety envelope and enforce policy guardrails."
description = "Policy-forward persona that monitors requests for safety violations."
tools = ["audit-log"]
safety_filters = ["default", "policy", "red-team"]
temperature = 0.25
top_p = 0.5
log_sink = "syslog"

[persona.rate_limits]
requests_per_minute = 120
tokens_per_minute = 45000

[[profile]]
name = "dev"
streaming = true
function_calling = true
log_sink = "stdout"
default_persona = "creative"

[[profile]]
name = "test"
streaming = false
function_calling = false
log_sink = "stderr"
default_persona = "analytical"

[[profile]]
name = "prod"
streaming = true
function_calling = true
log_sink = "/var/log/abi/agent.log"
default_persona = "guardian"
