#!/bin/bash
# Auto-generated by ralph-goal.sh. Exit 0 == goal achieved.
# Wrapped with a timeout so a hung verifier can never freeze the loop.
set -uo pipefail
__TIMEOUT_BIN=""
if command -v timeout  >/dev/null 2>&1; then __TIMEOUT_BIN="timeout";  fi
if [[ -z "$__TIMEOUT_BIN" ]] && command -v gtimeout >/dev/null 2>&1; then __TIMEOUT_BIN="gtimeout"; fi
__run() {
cd /Users/donald/abi && ./build.sh check
}
if [[ -n "$__TIMEOUT_BIN" ]]; then
  $__TIMEOUT_BIN 600s bash -c "$(declare -f __run); __run"
else
  __run
fi
