# Prometheus Configuration for WDBX Monitoring
# Optimized for validated performance metrics: 2,777+ ops/sec

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'wdbx-cluster'
    environment: 'staging'

rule_files:
  - "wdbx-alerts.yml"

scrape_configs:
  # WDBX Application Metrics
  - job_name: 'wdbx-staging'
    static_configs:
      - targets: ['wdbx-staging-service:9090']
    scrape_interval: 10s
    metrics_path: /metrics
    honor_labels: true
    params:
      format: ['prometheus']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: pod
      - source_labels: [__meta_kubernetes_namespace]
        target_label: namespace

  # WDBX Health Checks
  - job_name: 'wdbx-health'
    static_configs:
      - targets: ['wdbx-staging-service:8081']
    scrape_interval: 30s
    metrics_path: /health/metrics
    
  # Kubernetes Metrics
  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - wdbx-staging
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__

  # Node Exporter for System Metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Storage configuration
storage:
  tsdb:
    retention.time: 30d
    retention.size: 100GB
    min-block-duration: 2h
    max-block-duration: 25h
