## Summary
{{DESCRIPTION}}

## Generated Reference
{{AUTO_CONTENT}}

## Maintenance Notes
- This page is generated by `zig build gendocs`.
- Edit template source in `tools/gendocs/templates/docs/` for structural changes.
- Edit generator logic in `tools/gendocs/` for data model or rendering changes.
