## Summary
{{DESCRIPTION}}

## Feature Catalog

ABI uses 27 comptime-gated features defined in `src/core/feature_catalog.zig`.
Each feature has a `mod.zig` (real implementation) and `stub.zig` (disabled facade).

### Feature Flags

All features are enabled by default. Disable with `-Dfeat-<name>=false`.

| Feature | Flag | Parent | Module Path |
|---------|------|--------|-------------|
| gpu | `feat_gpu` | — | `src/features/gpu/` |
| ai | `feat_ai` | — | `src/features/ai/` |
| llm | `feat_llm` | ai | `src/features/ai/llm/` |
| embeddings | `feat_ai` | ai | `src/features/ai/embeddings/` |
| agents | `feat_ai` | ai | `src/features/ai/agents/` |
| training | `feat_training` | ai | `src/features/ai/training/` |
| database | `feat_database` | — | `src/features/database/` |
| network | `feat_network` | — | `src/features/network/` |
| observability | `feat_profiling` | — | `src/features/observability/` |
| web | `feat_web` | — | `src/features/web/` |
| personas | `feat_ai` | ai | `src/features/ai/profiles/` |
| cloud | `feat_cloud` | — | `src/features/cloud/` |
| analytics | `feat_analytics` | — | `src/features/analytics/` |
| auth | `feat_auth` | — | `src/features/auth/` |
| messaging | `feat_messaging` | — | `src/features/messaging/` |
| cache | `feat_cache` | — | `src/features/cache/` |
| storage | `feat_storage` | — | `src/features/storage/` |
| search | `feat_search` | — | `src/features/search/` |
| mobile | `feat_mobile` | — | `src/features/mobile/` |
| gateway | `feat_gateway` | — | `src/features/gateway/` |
| pages | `feat_pages` | — | `src/features/pages/` |
| benchmarks | `feat_benchmarks` | — | `src/features/benchmarks/` |
| reasoning | `feat_reasoning` | ai | `src/features/ai/reasoning/` |
| constitution | `feat_reasoning` | ai | `src/features/ai/constitution/` |
| compute | `feat_compute` | — | `src/features/compute/` |
| documents | `feat_documents` | — | `src/features/documents/` |
| desktop | `feat_desktop` | — | `src/features/desktop/` |

## Generated Reference
{{AUTO_CONTENT}}

## Maintenance Notes
- This page is generated by `zig build gendocs`.
- Edit template source in `tools/gendocs/templates/docs/` for structural changes.
- Canonical source: `src/core/feature_catalog.zig`
