//! Auto-generated stub module for feature: storage
//! This file was automatically generated by tools/stub_generator/
//! Manual edits may be overwritten.

const std = @import("std");
const config_module = @import("../../core/config/mod.zig");
const shared_types = @import("types.zig");

pub const types = shared_types;
pub const Error = shared_types.Error;
pub const Config = shared_types.Config;
pub const Context = shared_types.Context;
pub const State = shared_types.State;

pub const Error = error{
    StorageDisabled,
    WriteFailed,
    ReadFailed,
    NotFound,
    AlreadyExists,
};

pub const Context = struct {
    allocator: std.mem.Allocator = undefined,
    config: config_module.StorageDisabledConfig = .{},

    pub fn init(_: std.mem.Allocator, _: config_module.StorageDisabledConfig) !*Context {
        return error.StorageDisabled;
    }

    pub fn deinit(_: *Context) void {}
};

pub fn init(_: std.mem.Allocator, _: config_module.StorageDisabledConfig) Error!void {
    return error.StorageDisabled;
}

pub fn deinit() void {}

pub fn isEnabled() bool {
    return false;
}

test {
    std.testing.refAllDecls(@This());
}