//! Auto-generated stub module for feature: agents
//! This file was automatically generated by tools/stub_generator/
//! Manual edits may be overwritten.

const std = @import("std");
const config_module = @import("../../core/config/mod.zig");
const shared_types = @import("types.zig");

pub const types = shared_types;
pub const Error = shared_types.Error;
pub const Config = shared_types.Config;
pub const Context = shared_types.Context;

pub const Error = error{
    AgentsDisabled,
    AgentNotFound,
    MaxAgentsReached,
    ToolNotFound,
    ExecutionFailed,
};

pub const Context = struct {
    allocator: std.mem.Allocator = undefined,
    config: config_module.AgentsDisabledConfig = .{},

    pub fn init(_: std.mem.Allocator, _: config_module.AgentsDisabledConfig) !*Context {
        return error.AgentsDisabled;
    }

    pub fn deinit(_: *Context) void {}
};

pub fn init(_: std.mem.Allocator, _: config_module.AgentsDisabledConfig) Error!void {
    return error.AgentsDisabled;
}

pub fn deinit() void {}

pub fn isEnabled() bool {
    return false;
}

test {
    std.testing.refAllDecls(@This());
}