# abi bash completion; generated by `abi help --completion bash`
_abi_complete() {
  local cur cmd words
  COMPREPLY=()
  cur="${COMP_WORDS[COMP_CWORD]}"
  if [[ ${COMP_CWORD} -eq 1 ]]; then
    words="help complete train agent backends plugin auth twilio tui dashboard wdbx scheduler nn --tui "
    COMPREPLY=( $(compgen -W "$words" -- "$cur") )
    return 0
  fi
  cmd="${COMP_WORDS[1]}"
  case "$cmd" in
    help)
      words="--json --completion bash zsh fish help complete train agent backends plugin auth twilio tui dashboard wdbx scheduler nn --tui "
      COMPREPLY=( $(compgen -W "$words" -- "$cur") )
      ;;
    complete)
      words="--live --confirm --learn --soul --soul-alpha --stream --neural --model "
      COMPREPLY=( $(compgen -W "$words" -- "$cur") )
      ;;
    train)
      words=""
      COMPREPLY=( $(compgen -W "$words" -- "$cur") )
      ;;
    agent)
      words="plan train tui multi spawn browser os "
      COMPREPLY=( $(compgen -W "$words" -- "$cur") )
      ;;
    backends)
      words=""
      COMPREPLY=( $(compgen -W "$words" -- "$cur") )
      ;;
    plugin)
      words="list run "
      COMPREPLY=( $(compgen -W "$words" -- "$cur") )
      ;;
    auth)
      words="status logout signin "
      COMPREPLY=( $(compgen -W "$words" -- "$cur") )
      ;;
    twilio)
      words="simulate "
      COMPREPLY=( $(compgen -W "$words" -- "$cur") )
      ;;
    tui|--tui)
      words="--pane 1 2 3 4 5 system plugins storage wdbx scheduler memory --plain --no-color --compact --once --interval --json --list-panes "
      COMPREPLY=( $(compgen -W "$words" -- "$cur") )
      ;;
    dashboard)
      words="--pane 1 2 3 4 5 system plugins storage wdbx scheduler memory --plain --no-color --compact --once --interval --json --list-panes "
      COMPREPLY=( $(compgen -W "$words" -- "$cur") )
      ;;
    wdbx)
      words="db block query benchmark simulate cluster compute secure gpu api "
      COMPREPLY=( $(compgen -W "$words" -- "$cur") )
      ;;
    scheduler)
      words="status "
      COMPREPLY=( $(compgen -W "$words" -- "$cur") )
      ;;
    nn)
      words="train sample --jsonl --field --text --seed --n "
      COMPREPLY=( $(compgen -W "$words" -- "$cur") )
      ;;
  esac
}
complete -F _abi_complete abi
