#compdef abi
# abi zsh completion; generated by `abi help --completion zsh`
local -a commands
commands=(  help
  complete
  train
  agent
  backends
  plugin
  auth
  twilio
  tui
  dashboard
  wdbx
  scheduler
  nn
  --tui
)
if (( CURRENT == 2 )); then
  compadd -- $commands
  return
fi
local cmd="${words[2]}"
case "$cmd" in
    help)
      compadd -- --json --completion bash zsh fish help complete train agent backends plugin auth twilio tui dashboard wdbx scheduler nn --tui 
      ;;
    complete)
      compadd -- --live --confirm --learn --soul --soul-alpha --stream --neural --model 
      ;;
    train)
      compadd -- 
      ;;
    agent)
      compadd -- plan train tui multi spawn browser os 
      ;;
    backends)
      compadd -- 
      ;;
    plugin)
      compadd -- list run 
      ;;
    auth)
      compadd -- status logout signin 
      ;;
    twilio)
      compadd -- simulate 
      ;;
    tui|--tui)
      compadd -- --pane 1 2 3 4 5 system plugins storage wdbx scheduler memory --plain --no-color --compact --once --interval --json --list-panes 
      ;;
    dashboard)
      compadd -- --pane 1 2 3 4 5 system plugins storage wdbx scheduler memory --plain --no-color --compact --once --interval --json --list-panes 
      ;;
    wdbx)
      compadd -- db block query benchmark simulate cluster compute secure gpu api 
      ;;
    scheduler)
      compadd -- status 
      ;;
    nn)
      compadd -- train sample --jsonl --field --text --seed --n 
      ;;
esac
