# abi fish completion; generated by `abi help --completion fish`
complete -c abi -f
complete -c abi -n '__fish_use_subcommand' -a 'help complete train agent backends plugin auth twilio tui dashboard wdbx scheduler nn --tui '
complete -c abi -n '__fish_seen_subcommand_from help' -l json
complete -c abi -n '__fish_seen_subcommand_from help' -l completion -a 'bash zsh fish'
complete -c abi -n '__fish_seen_subcommand_from complete' -a ''
complete -c abi -n '__fish_seen_subcommand_from complete' -l live
complete -c abi -n '__fish_seen_subcommand_from complete' -l confirm
complete -c abi -n '__fish_seen_subcommand_from complete' -l learn
complete -c abi -n '__fish_seen_subcommand_from complete' -l soul
complete -c abi -n '__fish_seen_subcommand_from complete' -l soul-alpha
complete -c abi -n '__fish_seen_subcommand_from complete' -l stream
complete -c abi -n '__fish_seen_subcommand_from complete' -l neural
complete -c abi -n '__fish_seen_subcommand_from complete' -l model
complete -c abi -n '__fish_seen_subcommand_from train' -a ''
complete -c abi -n '__fish_seen_subcommand_from agent' -a 'plan train tui multi spawn browser os '
complete -c abi -n '__fish_seen_subcommand_from backends' -a ''
complete -c abi -n '__fish_seen_subcommand_from plugin' -a 'list run '
complete -c abi -n '__fish_seen_subcommand_from auth' -a 'status logout signin '
complete -c abi -n '__fish_seen_subcommand_from twilio' -a 'simulate '
complete -c abi -n '__fish_seen_subcommand_from tui --tui' -a ''
complete -c abi -n '__fish_seen_subcommand_from tui --tui' -l pane -a '1 2 3 4 5 system plugins storage wdbx scheduler memory '
complete -c abi -n '__fish_seen_subcommand_from tui --tui' -l plain
complete -c abi -n '__fish_seen_subcommand_from tui --tui' -l no-color
complete -c abi -n '__fish_seen_subcommand_from tui --tui' -l compact
complete -c abi -n '__fish_seen_subcommand_from tui --tui' -l once
complete -c abi -n '__fish_seen_subcommand_from tui --tui' -l interval
complete -c abi -n '__fish_seen_subcommand_from tui --tui' -l json
complete -c abi -n '__fish_seen_subcommand_from tui --tui' -l list-panes
complete -c abi -n '__fish_seen_subcommand_from dashboard' -a ''
complete -c abi -n '__fish_seen_subcommand_from dashboard' -l pane -a '1 2 3 4 5 system plugins storage wdbx scheduler memory '
complete -c abi -n '__fish_seen_subcommand_from dashboard' -l plain
complete -c abi -n '__fish_seen_subcommand_from dashboard' -l no-color
complete -c abi -n '__fish_seen_subcommand_from dashboard' -l compact
complete -c abi -n '__fish_seen_subcommand_from dashboard' -l once
complete -c abi -n '__fish_seen_subcommand_from dashboard' -l interval
complete -c abi -n '__fish_seen_subcommand_from dashboard' -l json
complete -c abi -n '__fish_seen_subcommand_from dashboard' -l list-panes
complete -c abi -n '__fish_seen_subcommand_from wdbx' -a 'db block query benchmark simulate cluster compute secure gpu api '
complete -c abi -n '__fish_seen_subcommand_from scheduler' -a 'status '
complete -c abi -n '__fish_seen_subcommand_from nn' -a 'train sample '
complete -c abi -n '__fish_seen_subcommand_from nn' -l jsonl
complete -c abi -n '__fish_seen_subcommand_from nn' -l field
complete -c abi -n '__fish_seen_subcommand_from nn' -l text
complete -c abi -n '__fish_seen_subcommand_from nn' -l seed
complete -c abi -n '__fish_seen_subcommand_from nn' -l n
