#!/usr/bin/env python3
"""
Automatic stub generator for the ABI Zig framework.

Generates stub.zig files from mod.zig files to maintain mod/stub parity.
Usage: python3 tools/stub_generator/generate_stubs.py <feature_directory>

This eliminates the 35% code duplication between mod.zig and stub.zig files
across the 71 feature modules in the codebase.
"""

import re
import os
import sys
from pathlib import Path
from dataclasses import dataclass
from typing import List, Optional, Tuple


@dataclass
class ExportDef:
    """Represents a public export from a mod.zig file."""

    name: str
    is_type: bool
    is_func: bool
    is_struct: bool
    is_const: bool


@dataclass
class StubTemplate:
    """Template data for generating stub files."""

    feature_name: str
    feature_flag: str
    error_name: str
    has_config: bool
    exports: List[ExportDef]
    has_context: bool
    has_init_deinit: bool


class StubGenerator:
    """Generates stub.zig files from mod.zig source files."""

    # Common patterns to extract from mod.zig
    PUB_EXPORT = re.compile(r"pub\s+const\s+(\w+)\s*=\s*(.+?);", re.MULTILINE)
    PUB_FN = re.compile(r"pub\s+fn\s+(\w+)\s*\([^)]*\)\s*(?:!)?(.+)?", re.MULTILINE)
    PUB_STRUCT = re.compile(r"pub\s+const\s+(\w+)\s*=\s*struct", re.MULTILINE)
    IS_ENABLED_FN = re.compile(r"pub\s+fn\s+isEnabled\s*\(\)", re.MULTILINE)
    INIT_FN = re.compile(r"pub\s+fn\s+init\s*\(", re.MULTILINE)
    DEINIT_FN = re.compile(r"pub\s+fn\s+deinit", re.MULTILINE)

    def __init__(self, feature_dir: Path):
        self.feature_dir = Path(feature_dir)
        self.feature_name = self.feature_dir.name
        self.mod_path = self.feature_dir / "mod.zig"
        self.types_path = self.feature_dir / "types.zig"

    def parse_mod_file(self) -> StubTemplate:
        """Parse the mod.zig file to extract exports and structure."""
        if not self.mod_path.exists():
            raise FileNotFoundError(f"mod.zig not found in {self.feature_dir}")

        content = self.mod_path.read_text()

        # Extract feature flag (from if/else pattern)
        feature_flag = self._extract_feature_flag(content)

        # Extract public exports
        exports = []

        # Find all pub const declarations
        for match in self.PUB_EXPORT.finditer(content):
            name = match.group(1)
            value = match.group(2)

            # Skip build_options, framework_config, and std imports
            if name in ("build_options", "framework_config", "std", "builtin"):
                continue

            is_type = (
                name.endswith("Config") or name.endswith("Error") or name == "types"
            )
            is_struct = "struct" in value
            is_const = not is_struct

            exports.append(
                ExportDef(
                    name=name,
                    is_type=is_type,
                    is_func=False,
                    is_struct=is_struct,
                    is_const=is_const,
                )
            )

        # Check for init/deinit
        has_init = bool(self.INIT_FN.search(content))
        has_deinit = bool(self.DEINIT_FN.search(content))
        has_is_enabled = bool(self.IS_ENABLED_FN.search(content))

        # Determine if there's a Context struct
        has_context = "Context" in content

        # Convert feature name to PascalCase
        error_name = self._to_pascal_case(self.feature_name) + "Disabled"

        return StubTemplate(
            feature_name=self.feature_name,
            feature_flag=feature_flag,
            error_name=error_name,
            has_config=any(e.name.endswith("Config") for e in exports),
            exports=exports,
            has_context=has_context,
            has_init_deinit=has_init and has_deinit,
        )

    def _extract_feature_flag(self, content: str) -> str:
        """Extract the feature flag from conditional imports."""
        # Look for pattern: build_options.feat_XX
        match = re.search(r"build_options\.(feat_\w+)", content)
        if match:
            return match.group(1)
        return f"feat_{self.feature_name}"

    def _to_pascal_case(self, name: str) -> str:
        """Convert snake_case or hyphen-case to PascalCase."""
        parts = re.split(r"[_-]", name)
        return "".join(p.capitalize() for p in parts)

    def generate_stub(self) -> str:
        """Generate the stub.zig content."""
        template = self.parse_mod_file()

        lines = [
            "//! Auto-generated stub module for feature: {feature}".format(
                feature=template.feature_name
            )
        ]
        lines.append(
            "//! This file was automatically generated by tools/stub_generator/"
        )
        lines.append("//! Manual edits may be overwritten.")
        lines.append("")

        # Imports
        lines.append('const std = @import("std");')
        lines.append('const config_module = @import("../../core/config/mod.zig");')

        # Import types.zig if it exists
        if self.types_path.exists():
            lines.append('const shared_types = @import("types.zig");')

        lines.append("")

        # Re-export types
        if self.types_path.exists():
            lines.append("pub const types = shared_types;")

            # Auto-export common types
            auto_types = ["Error", "Config", "Context", "Options", "State"]
            for type_name in auto_types:
                # Check if mentioned in content
                content = self.mod_path.read_text()
                if type_name in content:
                    lines.append(f"pub const {type_name} = shared_types.{type_name};")
            lines.append("")

        # Generate error set
        lines.append(f"pub const Error = error{{")
        lines.append(f"    {template.error_name},")

        # Common error variants
        common_errors = {
            "Agent": [
                "AgentNotFound",
                "MaxAgentsReached",
                "ToolNotFound",
                "ExecutionFailed",
            ],
            "Cache": ["CacheMiss", "KeyNotFound", "EvictionFailed", "InvalidEntry"],
            "Database": ["ConnectionFailed", "QueryFailed", "NotFound", "DuplicateKey"],
            "GPU": ["DeviceNotFound", "OutOfMemory", "KernelError", "InvalidArgument"],
            "Storage": ["WriteFailed", "ReadFailed", "NotFound", "AlreadyExists"],
            "Network": ["ConnectionFailed", "Timeout", "InvalidResponse", "TlsError"],
        }

        for key, errors in common_errors.items():
            if key.lower() in template.feature_name.lower():
                for err in errors:
                    lines.append(f"    {err},")

        lines.append("};")
        lines.append("")

        # Generate Context struct if needed
        if template.has_context:
            lines.append("pub const Context = struct {")
            lines.append("    allocator: std.mem.Allocator = undefined,")

            if template.has_config:
                lines.append(
                    f"    config: config_module.{template.error_name}Config = .{{}},"
                )

            lines.append("")
            lines.append(
                f"    pub fn init(_: std.mem.Allocator, _: config_module.{template.error_name}Config) !*Context {{"
            )
            lines.append(f"        return error.{template.error_name};")
            lines.append("    }")
            lines.append("")
            lines.append("    pub fn deinit(_: *Context) void {}")
            lines.append("};")
            lines.append("")

        # Generate init/deinit functions
        if template.has_init_deinit:
            lines.append(
                f"pub fn init(_: std.mem.Allocator, _: config_module.{template.error_name}Config) Error!void {{"
            )
            lines.append(f"    return error.{template.error_name};")
            lines.append("}")
            lines.append("")
            lines.append("pub fn deinit() void {}")
            lines.append("")

        # Generate isEnabled
        lines.append("pub fn isEnabled() bool {")
        lines.append("    return false;")
        lines.append("}")
        lines.append("")

        # Generate stub functions for remaining exports
        for export in template.exports:
            if export.name in ["types", "Error"]:
                continue

            if export.is_const and not export.is_struct:
                # Skip simple const values that we already handled
                continue

        # Generate stub struct exports
        for export in template.exports:
            if export.is_struct:
                lines.append(f"pub const {export.name} = struct {{")
                lines.append(
                    f"    pub fn init(_: std.mem.Allocator, _: config_module.{template.error_name}Config) !*Context {{"
                )
                lines.append(f"        return error.{template.error_name};")
                lines.append("    }")
                lines.append("")
                lines.append(
                    "    pub fn deinit(_: *{struct_name}) void {{}}".format(
                        struct_name=export.name
                    )
                )
                lines.append("};")
                lines.append("")

        # Add test block
        lines.append("test {")
        lines.append("    std.testing.refAllDecls(@This());")
        lines.append("}")

        return "\n".join(lines)

    def write_stub(self, dry_run: bool = False) -> None:
        """Generate and write the stub file."""
        stub_content = self.generate_stub()
        stub_path = self.feature_dir / "stub.zig"

        content_bytes = stub_content.encode("utf-8")

        # Check if content is different
        if stub_path.exists():
            existing = stub_path.read_text()
            if existing == stub_content:
                print(f"  ✓ {self.feature_name}/stub.zig - already up to date")
                return
            if not dry_run:
                # Create backup
                backup_path = stub_path.with_suffix(".zig.bak")
                backup_path.write_text(existing)
                print(f"  ↻ {self.feature_name}/stub.zig - backup created")

        if dry_run:
            print(f"  [DRY-RUN] Would generate {self.feature_name}/stub.zig")
        else:
            stub_path.write_bytes(content_bytes)
            print(f"  ✓ {self.feature_name}/stub.zig - generated")


def find_features(features_dir: Path) -> List[Path]:
    """Find all feature directories that contain mod.zig files."""
    features = []

    for item in features_dir.iterdir():
        if item.is_dir():
            mod_file = item / "mod.zig"
            stub_file = item / "stub.zig"

            # Only consider if both exist (follows mod/stub contract)
            if mod_file.exists() and stub_file.exists():
                features.append(item)
            elif mod_file.exists() and (item / "types.zig").exists():
                # Some features have mod.zig + types.zig but maybe missing stub
                pass

    return sorted(features)


def main():
    if len(sys.argv) < 2:
        print(
            "Usage: python3 tools/stub_generator/generate_stubs.py [--dry-run] <feature_dir | 'all'>"
        )
        print("")
        print("Examples:")
        print("  python3 tools/stub_generator/generate_stubs.py src/features/ai/agents")
        print("  python3 tools/stub_generator/generate_stubs.py --dry-run all")
        sys.exit(1)

    dry_run = "--dry-run" in sys.argv
    target = [arg for arg in sys.argv[1:] if not arg.startswith("--")][0]

    if dry_run:
        print("DRY RUN - No files will be modified")
        print("")

    if target.lower() == "all":
        # Process all features
        print("Scanning for features...")

        # Check multiple locations
        search_dirs = [
            Path("src/features"),
            Path("src/features/ai"),
            Path("src/features/core"),
            Path("src/features/network"),
            Path("src/connectors"),
        ]

        all_features = []
        for search_dir in search_dirs:
            if search_dir.exists():
                all_features.extend(find_features(search_dir))

        print(f"Found {len(all_features)} feature directories with mod/stub pairs")
        print("")

        for feature_dir in all_features:
            try:
                generator = StubGenerator(feature_dir)
                generator.write_stub(dry_run=dry_run)
            except Exception as e:
                print(f"  ✗ {feature_dir.name}: {e}")

        print("")
        print(f"Done! Processed {len(all_features)} features.")

    else:
        # Process single feature
        feature_dir = Path(target)
        if not feature_dir.exists():
            print(f"Error: Directory not found: {feature_dir}")
            sys.exit(1)

        generator = StubGenerator(feature_dir)
        generator.write_stub(dry_run=dry_run)


if __name__ == "__main__":
    main()
