//! Required declaration lists extracted from parity/mod.zig.
const abi = @import("abi");
const feature_catalog = abi.feature_catalog;

pub fn forFeature(comptime feature: feature_catalog.Feature) []const []const u8 {
    return forParitySpec(feature_catalog.paritySpec(feature));
}

pub fn forParitySpec(comptime spec: feature_catalog.ParitySpec) []const []const u8 {
    return switch (spec) {
        .gpu => @import("gpu.zig").required[0..],
        .ai => ai[0..],
        .database => database[0..],
        .network => network[0..],
        .observability => observability[0..],
        .web => web[0..],
        .analytics => analytics[0..],
        .cloud => cloud[0..],
        .auth => auth[0..],
        .messaging => messaging[0..],
        .cache => cache[0..],
        .storage => storage[0..],
        .search => search[0..],
        .ai_core => ai_core[0..],
        .ai_inference => ai_inference[0..],
        .ai_training => ai_training[0..],
        .ai_reasoning => ai_reasoning[0..],
        .mobile => mobile[0..],
        .gateway => gateway[0..],
        .pages => pages[0..],
        .benchmarks => benchmarks[0..],
    };
}

pub const ai = [_][]const u8{
    "Context",
    "Error",
    "Agent",
    "TrainingConfig",
    "TrainingResult",
    "Tool",
    "ToolResult",
    "ToolRegistry",
    "LlmEngine",
    "LlmModel",
    "LlmConfig",
    "StreamingGenerator",
    "StreamToken",
    "llm",
    "embeddings",
    "agents",
    "training",
    "streaming",
    "init",
    "deinit",
    "isEnabled",
    "isInitialized",
};

pub const database = [_][]const u8{
    "Context",
    "DatabaseHandle",
    "SearchResult",
    "VectorView",
    "Stats",
    "wdbx",
    "init",
    "deinit",
    "isEnabled",
    "isInitialized",
    "open",
    "close",
    "insert",
    "search",
};

pub const network = [_][]const u8{
    "Context",
    "Error",
    "NetworkConfig",
    "NodeInfo",
    "NodeRegistry",
    "init",
    "deinit",
    "isEnabled",
    "isInitialized",
    "defaultRegistry",
    "defaultConfig",
    "generateServiceId",
    "base64Encode",
    "base64Decode",
};

pub const web = [_][]const u8{
    "Context",
    "WebError",
    "Response",
    "HttpClient",
    "RequestOptions",
    "WeatherClient",
    "WeatherConfig",
    "JsonValue",
    "ParsedJson",
    "ChatHandler",
    "ChatRequest",
    "ChatResponse",
    "ChatResult",
    "PersonaRouter",
    "Route",
    "RouteContext",
    "handlers",
    "routes",
    "http",
    "init",
    "deinit",
    "isEnabled",
    "isInitialized",
    "get",
    "getWithOptions",
    "postJson",
    "freeResponse",
    "parseJsonValue",
    "isSuccessStatus",
};

pub const observability = [_][]const u8{
    "Context",
    "Error",
    "Counter",
    "Gauge",
    "FloatGauge",
    "Histogram",
    "MetricsCollector",
    "MetricsConfig",
    "MetricsSummary",
    "Tracer",
    "Span",
    "TraceId",
    "SpanId",
    "SpanKind",
    "SpanStatus",
    "ObservabilityBundle",
    "BundleConfig",
    "AlertManager",
    "AlertRule",
    "PrometheusExporter",
    "PrometheusConfig",
    "OtelExporter",
    "OtelConfig",
    "init",
    "deinit",
    "isEnabled",
    "isInitialized",
    "createCollector",
    "registerDefaultMetrics",
    "recordRequest",
    "recordError",
};

pub const analytics = [_][]const u8{
    "Context",
    "Event",
    "AnalyticsConfig",
    "AnalyticsError",
    "Engine",
    "Funnel",
    "Experiment",
    "init",
    "deinit",
    "isEnabled",
    "isInitialized",
};

pub const cloud = [_][]const u8{
    "CloudEvent",
    "CloudResponse",
    "CloudProvider",
    "CloudHandler",
    "CloudConfig",
    "CloudError",
    "HttpMethod",
    "InvocationMetadata",
    "Context",
    "ResponseBuilder",
    "Error",
    "detectProvider",
    "detectProviderWithAllocator",
    "runHandler",
    "init",
    "deinit",
    "isEnabled",
    "isInitialized",
    "aws_lambda",
    "gcp_functions",
    "azure_functions",
};

pub const auth = [_][]const u8{
    "AuthConfig",
    "AuthError",
    "Token",
    "Session",
    "Permission",
    "Context",
    "init",
    "deinit",
    "isEnabled",
    "isInitialized",
    "createToken",
    "verifyToken",
    "createSession",
    "checkPermission",
};

pub const gateway = [_][]const u8{
    "GatewayConfig",
    "RateLimitConfig",
    "RateLimitAlgorithm",
    "CircuitBreakerConfig",
    "CircuitBreakerState",
    "GatewayError",
    "HttpMethod",
    "Route",
    "MiddlewareType",
    "GatewayStats",
    "MatchResult",
    "RateLimitResult",
    "Context",
    "init",
    "deinit",
    "isEnabled",
    "isInitialized",
    "addRoute",
    "removeRoute",
    "getRoutes",
    "matchRoute",
    "checkRateLimit",
    "recordUpstreamResult",
    "stats",
    "getCircuitState",
    "resetCircuit",
};

pub const messaging = [_][]const u8{
    "MessagingConfig",
    "MessagingError",
    "Message",
    "Channel",
    "MessagingStats",
    "TopicInfo",
    "DeadLetter",
    "DeliveryResult",
    "SubscriberCallback",
    "Context",
    "init",
    "deinit",
    "isEnabled",
    "isInitialized",
    "publish",
    "subscribe",
    "unsubscribe",
    "listTopics",
    "topicStats",
    "getDeadLetters",
    "clearDeadLetters",
    "messagingStats",
};

pub const cache = [_][]const u8{
    "CacheConfig",
    "EvictionPolicy",
    "CacheError",
    "CacheEntry",
    "CacheStats",
    "Context",
    "init",
    "deinit",
    "isEnabled",
    "isInitialized",
    "get",
    "put",
    "putWithTtl",
    "delete",
    "contains",
    "clear",
    "size",
    "stats",
};

pub const storage = [_][]const u8{
    "StorageConfig",
    "StorageBackend",
    "StorageError",
    "StorageObject",
    "ObjectMetadata",
    "StorageStats",
    "Context",
    "init",
    "deinit",
    "isEnabled",
    "isInitialized",
    "putObject",
    "putObjectWithMetadata",
    "getObject",
    "deleteObject",
    "objectExists",
    "listObjects",
    "stats",
};

pub const search = [_][]const u8{
    "SearchConfig",
    "SearchError",
    "SearchResult",
    "SearchIndex",
    "SearchStats",
    "Context",
    "init",
    "deinit",
    "isEnabled",
    "isInitialized",
    "createIndex",
    "deleteIndex",
    "indexDocument",
    "deleteDocument",
    "query",
    "stats",
};

pub const ai_core = [_][]const u8{
    "Context",
    "Error",
    "isEnabled",
    "Agent",
    "ToolRegistry",
    "PromptBuilder",
    "ModelRegistry",
    "createAgent",
    "createRegistry",
};

pub const ai_inference = [_][]const u8{
    "Context",
    "Error",
    "isEnabled",
    "llm",
    "embeddings",
    "streaming",
    "transformer",
};

pub const ai_training = [_][]const u8{
    "Context",
    "Error",
    "isEnabled",
    "TrainingConfig",
    "TrainableModel",
    "train",
    "trainWithResult",
};

pub const ai_reasoning = [_][]const u8{
    "Context",
    "Error",
    "isEnabled",
    "abbey",
    "explore",
    "orchestration",
    "documents",
};

pub const mobile = [_][]const u8{
    "MobileConfig",
    "MobilePlatform",
    "MobileError",
    "LifecycleState",
    "SensorData",
    "Context",
    "init",
    "deinit",
    "isEnabled",
    "isInitialized",
    "getLifecycleState",
    "readSensor",
    "sendNotification",
};

pub const pages = [_][]const u8{
    "PagesConfig",
    "PagesError",
    "HttpMethod",
    "MetadataEntry",
    "TemplateVar",
    "TemplateRef",
    "PageContent",
    "Page",
    "PageMatch",
    "RenderResult",
    "PagesStats",
    "Context",
    "init",
    "deinit",
    "isEnabled",
    "isInitialized",
    "addPage",
    "removePage",
    "getPage",
    "matchPage",
    "renderPage",
    "listPages",
    "stats",
};

pub const benchmarks = [_][]const u8{
    "Config",
    "BenchmarksError",
    "Context",
    "isEnabled",
};
