//! Auto-generated stub module for feature: gpu
//! This file was automatically generated by tools/stub_generator/
//! Manual edits may be overwritten.

const std = @import("std");
const config_module = @import("../../core/config/mod.zig");
const shared_types = @import("types.zig");

pub const types = shared_types;
pub const Error = shared_types.Error;
pub const Config = shared_types.Config;
pub const Context = shared_types.Context;
pub const Options = shared_types.Options;

pub const Error = error{
    GpuDisabled,
    DeviceNotFound,
    OutOfMemory,
    KernelError,
    InvalidArgument,
};

pub const Context = struct {
    allocator: std.mem.Allocator = undefined,
    config: config_module.GpuDisabledConfig = .{},

    pub fn init(_: std.mem.Allocator, _: config_module.GpuDisabledConfig) !*Context {
        return error.GpuDisabled;
    }

    pub fn deinit(_: *Context) void {}
};

pub fn init(_: std.mem.Allocator, _: config_module.GpuDisabledConfig) Error!void {
    return error.GpuDisabled;
}

pub fn deinit() void {}

pub fn isEnabled() bool {
    return false;
}

test {
    std.testing.refAllDecls(@This());
}