name: Zig CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  build-test-run:
    name: Build, Test & Run (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        zig-version: ["0.13.0"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run zig fmt --check
        run: zig fmt --check
      - name: Setup Zig
        uses: actions/setup-zig@v1
        with:
          version: ${{ matrix.zig-version }}

      - name: Build
        run: zig build

      - name: Test
        run: zig build test

      - name: Run binary
        run: zig build run
        # Ensure the run does not block indefinitely
        timeout-minutes: 2
