//! Auto-generated stub module for feature: cache
//! This file was automatically generated by tools/stub_generator/
//! Manual edits may be overwritten.

const std = @import("std");
const config_module = @import("../../core/config/mod.zig");
const shared_types = @import("types.zig");

pub const types = shared_types;
pub const Error = shared_types.Error;
pub const Config = shared_types.Config;
pub const Context = shared_types.Context;
pub const State = shared_types.State;

pub const Error = error{
    CacheDisabled,
    CacheMiss,
    KeyNotFound,
    EvictionFailed,
    InvalidEntry,
};

pub const Context = struct {
    allocator: std.mem.Allocator = undefined,
    config: config_module.CacheDisabledConfig = .{},

    pub fn init(_: std.mem.Allocator, _: config_module.CacheDisabledConfig) !*Context {
        return error.CacheDisabled;
    }

    pub fn deinit(_: *Context) void {}
};

pub fn init(_: std.mem.Allocator, _: config_module.CacheDisabledConfig) Error!void {
    return error.CacheDisabled;
}

pub fn deinit() void {}

pub fn isEnabled() bool {
    return false;
}

test {
    std.testing.refAllDecls(@This());
}